(defun palindromep (n)
  (do ((num n (floor num 10))
       (rev 0 (+ (* 10 rev) (mod num 10))))
      ((zerop num) (= n rev))))

(defun solution ()
  (let ((max 0))
    (dotimes (i 899)
      (dotimes (j 899)
        (let ((product (* (+ i 100) (+ j 100))))
          (if (and (palindromep product)
                   (> product max))
              (setf max product)))))
    max))
