(defparameter *memo* (make-hash-table))
(setf (gethash 1 *memo*) 1)

(defun collatz (n)
  (assert (gethash 1 *memo*))
  (or (gethash n *memo*)
      (setf (gethash n *memo*)
            (if (evenp n)
                (1+ (collatz (/ n 2)))
                (1+ (collatz (+ (* 3 n) 1)))))))

(defun solution ()
  (let ((max-steps 1)
        (num 1))
    (dotimes (i 999999 num)
      (let ((steps (collatz (1+ i))))
        (when (> steps max-steps)
          (setf max-steps steps)
          (setf num (1+ i)))))))
